import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Nav from './Nav'

const Layout = ({children}) => {
  return (
    <div className={styles.container}>
        <Head>
            <title>My Notes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />

        <main className={styles.main}>
            {children}
        </main>

        <footer className={styles.footer}>
            <div className={styles.footerLinkContainer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
                </a>
            </div>
            <div className={styles.footerLinkContainer}>
                <a
                href="https://www.mongodb.com/"
                target="_blank"
                rel="noopener noreferrer"
                >
                MongoDB{' '}
                <span className={styles.logo}>
                    <Image src="/mongodb.svg" alt="mongodb Logo" width={20} height={20} />
                </span>
                </a>
            </div>
            <div className={styles.footerLinkContainer}>
                <a
                href="https://github.com/rakanishudDev/mynotes-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Github repo{' '}
                <span className={styles.logo}>
                    <Image src="/github.svg" alt="github Logo" width={20} height={20} />
                </span>
                </a>
            </div>
        </footer>
    </div>
  )
}

export default Layout